/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#425a81",
        "inverse-surface": "#2d3133",
        "surface-alt": "#F8FAFC",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary": "#ffffff",
        "secondary-container": "#bad3ff",
        "surface": "#f7f9fb",
        "border-light": "#E2E8F0",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#000703",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#bec8cf",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#004d66",
        "inverse-primary": "#77d1fd",
        "secondary": "#475f86",
        "inverse-on-surface": "#eff1f3",
        "primary": "#006686",
        "surface-container-high": "#e6e8ea",
        "background": "#f7f9fb",
        "primary-fixed": "#c0e8ff",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "outline": "#6f787f",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#00885d",
        "on-secondary-fixed": "#001b3c",
        "text-main": "#0F172A",
        "secondary-fixed-dim": "#afc7f4",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#ffffff",
        "secondary-fixed": "#d5e3ff",
        "surface-container": "#eceef0",
        "surface-tint": "#006687",
        "error": "#ba1a1a",
        "tertiary": "#006c49",
        "on-primary-fixed": "#001e2b",
        "primary-container": "#0080a8",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#77d1fd",
        "white": "#FFFFFF",
        "on-surface-variant": "#3f484e",
        "on-secondary-fixed-variant": "#2f476d",
        "text-muted": "#475569",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "deep-corporate": "#132E52",
        "tech-cyan": "#0080A8",
        "brand-green": "#10B981"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "section-gap": "80px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "geist": ["Geist", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "jetbrains-mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
